export const Images: any = {
  missions: {
    "9th: Eternal War": {
      "Incisive Strike": require("../assets/images/9thEternalWar/incisive.png"),
      Outriders: require("../assets/images/9thEternalWar/outriders.png"),
      Encircle: require("../assets/images/9thEternalWar/encircle.png"),
    },
    "Grand Tournament 2021": {
      Crossfire: require("../assets/images/GrandTournament2021/Crossfire2020.png"),
      Resupply: require("../assets/images/GrandTournament2021/Resupply2020.png"),
      Raid: require("../assets/images/GrandTournament2021/Raid2020.png"),
      "Centre Ground": require("../assets/images/GrandTournament2021/CentreGround2020.png"),
      Ascension: require("../assets/images/GrandTournament2021/Ascension2020.png"),
      "Forward Push": require("../assets/images/GrandTournament2021/ForwardPush2020.png"),
      "Rise of the Machine Spirit": require("../assets/images/GrandTournament2021/RiseOfTheMachineSpirit2020.png"),
      "Show of Force": require("../assets/images/GrandTournament2021/ShowOfForce2020.png"),
      "Reconaissance Mission": require("../assets/images/GrandTournament2021/ReconnaissanceMission2020.png"),
      "Retrieval Mission": require("../assets/images/GrandTournament2021/RetrievalMission2020.png"),
      "Scorched Earth": require("../assets/images/GrandTournament2021/ScorchedEarth2020.png"),
      "Vital Intelligence": require("../assets/images/GrandTournament2021/VitalIntelligence2020.png"),
      "Surround and Destroy": require("../assets/images/GrandTournament2021/SurroundAndDestroy2020.png"),
      "Battle Lines": require("../assets/images/GrandTournament2021/BattleLines2020.png"),
      "The Scouring": require("../assets/images/GrandTournament2021/TheScouring2020.png"),
      Overrun: require("../assets/images/GrandTournament2021/Overrun2020.png"),
      "Sweep and Clear": require("../assets/images/GrandTournament2021/SweepAndClear2020.png"),
      "Priority Target": require("../assets/images/GrandTournament2021/PriorityTarget2020.png"),
    },
  },
  icons: {
    "Adeptus Custodes": require("../assets/images/icons/Adeptus_Custodes.png"),
    "Adeptus Mechanicus": require("../assets/images/icons/Adeptus_Mechanicus.png"),
    "Adepta Sororitas": require("../assets/images/icons/Adepta_Sororitas.png"),
    "Blood Angels": require("../assets/images/icons/Blood_Angels.png"),
    "Dark Angels": require("../assets/images/icons/Dark_Angels.png"),
    Deathwatch: require("../assets/images/icons/Deathwatch.png"),
    "Grey Knights": require("../assets/images/icons/Grey_Knights.png"),
    "Space Marines": require("../assets/images/icons/Space_Marines.png"),
    "Space Wolfs": require("../assets/images/icons/Space_Wolfs.png"),
    Aeldari: require("../assets/images/icons/Aeldari.png"),
    "Astra Militarum": require("../assets/images/icons/Astra_Militarum.png"),
    "Chaos Daemons": require("../assets/images/icons/Chaos_Daemons.png"),
    "Chaos Knights": require("../assets/images/icons/Chaos_Knights.png"),
    Drukhari: require("../assets/images/icons/Drukhari.png"),
    "Chaos Space Marines": require("../assets/images/icons/Chaos_Space_Marines.png"),
    "Death Guard": require("../assets/images/icons/Death_Guard.png"),
    "Thousand Sons": require("../assets/images/icons/Thousand_Sons.png"),
    "Genestealer Cults": require("../assets/images/icons/Genestealer_Cults.png"),
    Harlequins: require("../assets/images/icons/Harlequins.png"),
    "Imperial Knights": require("../assets/images/icons/Imperial_Knights.png"),
    Necrons: require("../assets/images/icons/Necrons.png"),
    Orks: require("../assets/images/icons/Orks.png"),
    "T'au": require("../assets/images/icons/T_au.png"),
    Tyranids: require("../assets/images/icons/Tyranids.png"),
    Ultramarines: require("../assets/images/icons/Ultramarines.png"),
    "Black Templars": require("../assets/images/icons/Black_Templars.png"),
    Salamanders: require("../assets/images/icons/Salamanders.png"),
    "Imperial Fists": require("../assets/images/icons/Imperial_Fists.png"),
    "White Scars": require("../assets/images/icons/White_Scars.png"),
    "Iron Hands": require("../assets/images/icons/Iron_Hands.png"),
    "Raven Guard": require("../assets/images/icons/Raven_Guard.png"),
    Craftworlds: require("../assets/images/icons/Craftworlds.png"),
    Ynnari: require("../assets/images/icons/Ynnari.png"),
  },
};
